/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itomarevised;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Regusers extends javax.swing.JFrame {

    /**
     * Creates new form Regusers
     */
    public Regusers() {
        initComponents();        
        setIcon();
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        int width = (int)tool.getScreenSize().getWidth();
        int height = (int)tool.getScreenSize().getWidth();
        
        this.setSize(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yellowPanel = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        clearButton = new java.awt.Button();
        goButton = new java.awt.Button();
        regnewuser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        whitePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Bookshelf");
        setResizable(false);

        yellowPanel.setBackground(new java.awt.Color(255, 255, 51));

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        back.setText("BACK");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTERED");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reguser white.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERS");

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        searchbar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbarMouseClicked(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        clearButton.setLabel("CLEAR");
        clearButton.setPreferredSize(new java.awt.Dimension(65, 30));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        goButton.setBackground(new java.awt.Color(0, 204, 102));
        goButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        goButton.setLabel("GO");
        goButton.setPreferredSize(new java.awt.Dimension(65, 30));
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        regnewuser.setBackground(new java.awt.Color(255, 255, 255));
        regnewuser.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        regnewuser.setText("REGISTER NEW USER");
        regnewuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        regnewuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regnewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnewuserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Search");

        javax.swing.GroupLayout yellowPanelLayout = new javax.swing.GroupLayout(yellowPanel);
        yellowPanel.setLayout(yellowPanelLayout);
        yellowPanelLayout.setHorizontalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yellowPanelLayout.createSequentialGroup()
                        .addComponent(regnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(yellowPanelLayout.createSequentialGroup()
                        .addComponent(jLayeredPane1)
                        .addGap(14, 14, 14))))
            .addGroup(yellowPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(back)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        yellowPanelLayout.setVerticalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(back)
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(regnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));

        borrowersTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        borrowersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower ID", "Last Name", "Firt Name", "Middle Name", "Email Address", "Contact Number", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(borrowersTable);
        if (borrowersTable.getColumnModel().getColumnCount() > 0) {
            borrowersTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(1).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(2).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(3).setResizable(false);
            borrowersTable.getColumnModel().getColumn(3).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(4).setResizable(false);
            borrowersTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(5).setResizable(false);
            borrowersTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            borrowersTable.getColumnModel().getColumn(6).setResizable(false);
            borrowersTable.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        javax.swing.GroupLayout whitePanelLayout = new javax.swing.GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(yellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yellowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.hide();
        new Menu().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void searchbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseClicked
        searchbar.setText(null);
    }//GEN-LAST:event_searchbarMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel)borrowersTable.getModel();
        table.setRowCount(0);
        showBorrowersList("SELECT * FROM `borrowers`");
        searchbar.setText(null);        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void regnewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnewuserActionPerformed
        new Newuser().setVisible(true);
    }//GEN-LAST:event_regnewuserActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        DefaultTableModel table = (DefaultTableModel)borrowersTable.getModel();
        table.setRowCount(0);
        String query;        
        query = "SELECT * FROM `borrowers` WHERE fname = '"+searchbar.getText()+"' OR "
                + "lname = '"+searchbar.getText()+"' OR mname = '"+searchbar.getText()+"'"
                + "OR borrower_id = '"+searchbar.getText()+"'";                    
        boolean result = false;
        result = isFound(searchbar.getText(),result, query);
        if(result == false){
            JOptionPane.showMessageDialog(null, "User Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            showBorrowersList("SELECT * FROM `borrowers`");
            searchbar.setText(null);
        }else{            
            showBorrowersList(query);
        }
    }//GEN-LAST:event_searchbarActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel)borrowersTable.getModel();
        table.setRowCount(0);
        String query;        
        query = "SELECT * FROM `borrowers` WHERE fname = '"+searchbar.getText()+"' "
                + "OR lname = '"+searchbar.getText()+"' OR mname = '"+searchbar.getText()+"' "
                + "OR borrower_id = '"+searchbar.getText()+"'";          
        boolean result = false;
        result = isFound(searchbar.getText(),result, query);
        if(result == false){
            JOptionPane.showMessageDialog(null, "User Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            showBorrowersList("SELECT * FROM `borrowers`");
            searchbar.setText(null);
        }else{            
            showBorrowersList(query);
        }
    }//GEN-LAST:event_goButtonActionPerformed
    
    public Connection getConnection(){
        Connection connection;
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/itoma?user=root&password=");
            return connection;
        }catch(Exception ex){
            ex.printStackTrace();
            return null;
        }
    }
        
    public ArrayList<Borrower> showBorrowersList(String query){
        ArrayList<Borrower> list = new ArrayList<Borrower>();
        Connection connection = getConnection();
        
        Statement stmnt;
        ResultSet result;
        
        try{
            stmnt = connection.createStatement();
            result = stmnt.executeQuery(query);
            Borrower b;
            while(result.next()){
                b = new Borrower(result.getInt("borrower_id"),
                        result.getString("fname"),result.getString("lname"),
                        result.getString("mname"),result.getString("gender").charAt(0),
                        result.getString("email_address"),result.getString("contact_no"), 
                        result.getString("current_address"),result.getString("borrower_type"));
                list.add(b);
            }
            
            DefaultTableModel table = (DefaultTableModel)borrowersTable.getModel();
            table.setRowCount(0);
            Object[] row = new Object[7];
            for(int x = 0; x < list.size(); x++){
                row[0] = list.get(x).getBorrower_id();
                row[1] = list.get(x).getLname();
                row[2] = list.get(x).getFname();
                row[3] = list.get(x).getMname();
                row[4] = list.get(x).getEmail_address();
                row[5] = list.get(x).getContact_no();
                row[6] = list.get(x).getBorrower_type();

                table.addRow(row);
            }
        
        }catch(Exception e){
            e.printStackTrace();
            
        }
        
        return list;
    }
    public boolean isFound(String search, boolean found, String query){        
        ArrayList<Borrower> list = new ArrayList<Borrower>();
        Connection connection = getConnection();
        
        Statement stmnt;
        ResultSet result;
        
        try{
            stmnt = connection.createStatement();
            result = stmnt.executeQuery(query);
            Borrower b;
            while(result.next()){
                b = new Borrower(result.getInt("borrower_id"),
                        result.getString("fname"),result.getString("lname"),
                        result.getString("mname"),result.getString("gender").charAt(0),
                        result.getString("email_address"),result.getString("contact_no"), 
                        result.getString("current_address"),result.getString("borrower_type"));
                list.add(b);
            }
            for(int i = 0; i < list.size(); i++){
                if(list.get(i).getFname().equalsIgnoreCase(search) 
                        || list.get(i).getMname().equalsIgnoreCase(search) 
                        || list.get(i).getLname().equalsIgnoreCase(search) 
                        || list.get(i).getBorrower_id() == Integer.parseInt(search)){
                    found =  true;           
                } 
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        return found;        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTable borrowersTable;
    private java.awt.Button clearButton;
    private java.awt.Button goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regnewuser;
    private javax.swing.JTextField searchbar;
    private javax.swing.JPanel whitePanel;
    private javax.swing.JPanel yellowPanel;
    // End of variables declaration//GEN-END:variables
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("/icons/frameicon2.png")));
    }
}
